name: Build Theos Tweak

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential git curl libxml2-utils clang lld

      - name: Setup Theos & SDKs
        run: |
          git clone --recursive https://github.com/theos/theos.git $HOME/theos
          rm -rf $HOME/theos/sdks
          git clone --depth=1 https://github.com/theos/sdks.git $HOME/theos/sdks
          echo "$HOME/theos/bin" >> $GITHUB_PATH

      - name: Build deb package
        run: |
          export THEOS=$HOME/theos
          make package THEOS_PACKAGE_SCHEME=rootless

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: BountyMod-deb
          path: packages/*.deb
